version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=pgsqldb
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SERVER_PORT=8080
    depends_on:
      - pgsqldb

  pgsqldb:
    image: postgres:16.4
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - pgsqldb

volumes:
  pgsqldata:
